server:
  port: 8082

# Dubbo 方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    timeout: 3000
